[versions]
junit-jupiter = "5.12.0-M1"
checkstyle = "10.21.2"
pmd = "7.10.0"
spotbugs-gradle-plugin = "6.1.3"
spotbugs = "4.9.0"
findsecbugs = "1.12.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit.jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
pmd = { module = "net.sourceforge.pmd:pmd-core", version.ref = "pmd" }
spotbugs = { module = "com.github.spotbugs:spotbugs", version.ref = "spotbugs" }
findsecbugs = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }

[plugins]
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs.gradle.plugin" }
