---
id_firefox_prefs:
  #
  #  Performance.
  #
  accessibility.force_disabled: 1
  browser.touchmode.auto: false
  narrate.enabled: false
  dom.use_watchdog: false
  javascript.options.wasm_branch_hinting: true
  javascript.options.wasm_relaxed_simd: true
  #
  #  GPU.
  #
  gfx.webrender.compositor: true
  gfx.webrender.all: true
  layers.gpu-process.enabled: true
  gfx.canvas.accelerated: true
  #
  #  Startup.
  #
  browser.laterrun.enabled: false
  browser.shell.checkDefaultBrowser: false
  browser.startup.page: 3
  #
  #  Telemetry, reports, and others.
  #
  browser.crashReports.crashPull: false
  browser.crashReporter.memtest: false
  browser.crashReports.unsubmittedCheck.enabled: false
  browser.tabs.crashReporting.sendReport: false
  app.shield.optoutstudies.enabled: false
  #
  #  Recommendations and personalization.
  #
  browser.discovery.enabled: false
  browser.discovery.containers.enabled: false
  browser.shopping.experience2023.active: false
  browser.places.interactions.enabled: false
  browser.topsites.contile.enabled: false
  browser.vpn_promo.enabled: false
  #
  #  Filters, protection.
  #
  browser.safebrowsing.downloads.enabled: false
  browser.xul.error_pages.show_safe_browsing_details_on_load: true
  #
  #  UI.
  #
  middlemouse.paste: false
  browser.aboutConfig.showWarning: false
  browser.menu.showViewImageInfo: true
  widget.gtk.overlay-scrollbars.enabled: false
  ui.prefersReducedMotion: true
  general.smoothScroll: false

  browser.newtabpage.enabled: false
  browser.startup.homepage: chrome://browser/content/blanktab.html

  browser.backup.preferences.ui.enabled: true
  browser.preferences.experimental: true
  browser.preferences.experimental.hidden: false
  browser.preferences.moreFromMozilla: true
  browser.privacySegmentation.preferences.show: true
  browser.contentblocking.customBlockList.preferences.ui.enabled: true
  browser.uiCustomization.state:
    {
      "currentVersion": 22,
      "placements": {
        "nav-bar": [
          "sidebar-button",
          "back-button",
          "forward-button",
          "stop-reload-button",
          "vertical-spacer",
          "urlbar-container",
          "screenshot-button",
          "downloads-button",
          "unified-extensions-button"
        ],
        "TabsToolbar": [
          "tabbrowser-tabs",
          "new-tab-button",
          "alltabs-button",
          "firefox-view-button"
        ]
      }
    }
  #
  #  Sidebar.
  #
  browser.contextual-password-manager.enabled: false
  browser.ml.chat.enabled: false
  sidebar.animation.enabled: false
  sidebar.revamp: true
  sidebar.main.tools: history,bookmarks
  #
  #  Search.
  #
  browser.search.region: US
  browser.urlbar.maxHistoricalSearchSuggestions: 10
  #
  #  Tabs.
  #
  browser.tabs.groups.enabled: true
  browser.tabs.groups.smart.enabled: false
  browser.tabs.fadeOutExplicitlyUnloadedTabs: true
  browser.tabs.fadeOutUnloadedTabs: true
  browser.sessionstore.restore_hidden_tabs: true
  browser.tabs.unloadOnLowMemory: true
  browser.tabs.insertRelatedAfterCurrent: true
  #
  #  Bookmarks.
  #
  browser.bookmarks.editDialog.firstEditField: folderMenuList
  browser.bookmarks.editDialog.showForNewBookmarks: true
  browser.bookmarks.editDialog.maxRecentFolders: 40
  browser.bookmarks.openInTabClosesMenu: false
  browser.bookmarks.max_backups: 10
  browser.tabs.loadBookmarksInTabs: true
  browser.toolbars.bookmarks.visibility: always
  browser.toolbars.bookmarks.showOtherBookmarks: true
  #
  #  Permissions.
  #
  dom.webnotifications.enabled: false
  dom.push.enabled: false
  geo.enabled: false
  permissions.media.show_always_ask.enabled: true
  privacy.webrtc.globalMuteToggles: true
  dom.block_download_insecure: false
  #
  #  Features.
  #
  browser.translations.enable: false
  browser.translations.automaticallyPopup: false
  print.enabled: false
  reader.parse-on-load.enabled: false

  signon.rememberSignons: false
  signon.firefoxRelay.feature: false
  extensions.formautofill.creditCards.enabled: false
  extensions.formautofill.addresses.enabled: false

  extensions.pocket.enabled: false
  extensions.pictureinpicture.enable_picture_in_picture_overrides: false
  #
  #  Containers.
  #
  privacy.userContext.enabled: false
  privacy.userContext.ui.enabled: false
  #
  #  PDF.
  #
  pdfjs.enableScripting: false
  #
  #  Media.
  #
  media.getusermedia.audio.processing.aec.enabled: false
  media.getusermedia.audio.processing.agc.enabled: false
  media.getusermedia.audio.processing.agc2.forced: false
  media.getusermedia.audio.processing.platform.enabled: false
  media.getusermedia.audio.processing.transient.enabled: false
  media.getusermedia.audio.processing.noise.enabled: false
  media.getusermedia.audio.processing.hpf.enabled: false
  media.hevc.enabled: true
  media.hardware-video-decoding.enabled: true
  media.webrtc.hw.h264.enabled: true
  media.webspeech.synth.enabled: false

id_chromium_flags:
  #
  #  Look.
  #
  - disable-smooth-scrolling
  - disable-login-animations
  - enable-bookmark-undo

  # - force-dark-mode
  # - device-scale-factor
  # - force-device-scale-factor
  # - disable-gpu-vsync
  # - disable-frame-rate-limit
  #
  #  GPU.
  #
  # - sync-point-graph-validation
  - disable-gpu-watchdog
  - ignore-gpu-blocklist
  - enable-zero-copy
  - enable-accelerated-2d-canvas
  - enable-gpu-rasterization
  - enable-gpu-memory-buffer-video-frames
  - enable-gpu-memory-buffer-compositor-resources
  - enable-skia-graphite
  # - egl
  # - gl
  # - gles
  # - use-angle=gl
  # - use-gl
  - use-vulkan
  #
  #  Startup.
  #
  - disable-first-run-ui
  - no-first-run
  - restore-last-session
  - no-default-browser-check
  - disable-breakpad
  - disable-crash-reporter
  - disable-crashpad-for-testing
  - disable-crashpad-forwarding
  # - new-window
  # - user-data-dir
  #
  #  Performance.
  #
  # - disable-namespace-sandbox
  - disable-stack-profiler
  - disable-logging
  #
  #  Desktop Environment.
  #
  # kwallet, kwallet5, kwallet6, gnome-libsecret
  - password-store=basic
  - use-mock-keychain
  - gtk-version=4
  - disable-gtk-ime
  # - ozone-platform
  - ozone-platform-hint=auto
  - wayland-session-management
  - wayland-linux-drm-syncobj
  - wayland-ui-scaling
  - wayland-text-input-v3
  - use-wayland-explicit-grab
  #
  #  Permissions and APIs.
  #
  # - autoplay-policy=no-user-gesture-required
  - default-country-code=US
  - disable-speech-api
  - disable-speech-synthesis-api
  - disable-notifications
  - disable-widevine
  #
  #  Experiments.
  #
  - enable-quic
  - enable-experimental-webassembly-features
  - enable-webassembly-lazy-compilation
  - enable-experimental-web-platform-features
  - enable-experimental-extension-apis
  - javascript-harmony

#
# --enable-features
#
id_chromium_features_enable:
  # - MiddleClickAutoscroll
  # - DefaultANGLEVulkan
  - AcceleratedVideoDecodeLinuxGL
  - AcceleratedVideoEncoder
  - VaapiVideoDecoder
  - VaapiIgnoreDriverChecks
  - BookmarksTreeView
  - CompareManagementInterface
  - ExtensionsMenuAccessControl
  - LocalHistoryZeroSuggestBeyondNTP
  - ParallelDownloading
  - PdfPortfolio
  - PrivacyPolicyInsights
  - RustyPng
  - SupportToolScreenshot
  - V8VmFuture
  - WebAssemblyLazyCompilation
  - ZeroCopyRBPPartialRasterWithGpuCompositor

#
# --disable-features
#
id_chromium_features_disable:
  - AutofillEnableSaveAndFill
  - AutofillShowTypePredictions
  - AutofillUpstream
  - CameraMicEffects
  - ChromeWideEchoCancellation
  - Glic
  - WebRtcAllowInputVolumeAdjustment
  - WebRtcPipeWireCamera
  - fill-on-account-select

#
# https://www.chromium.org/administrators/configuring-other-preferences
#
id_chromium_prefs:
  {
    "autofill": {
      "credit_card_enabled": false,
      "profile_enabled": false
    },
    "bookmark_bar": {
      "show_on_all_tabs": true
    },
    "password_manager": {
      "autofillable_credentials_account_store_login_database": false,
      "autofillable_credentials_profile_store_login_database": false
    },
    "session": {
      "restore_on_startup": 1
    },
    "settings": {
      "force_google_safesearch": false
    },
    "side_panel": {
      "is_right_aligned": false
    },
    "signin": {
      "allowed": false
    },
    "tab_search": {
      "is_right_aligned": true
    },
    "translate": {
      "enabled": false
    },
    "toolbar": {
      "pinned_actions": [
        "kActionShowChromeLabs",
        "kActionSidePanelShowBookmarks",
        "kActionSidePanelShowHistoryCluster"
      ],
      "pinned_cast_migration_complete": true,
      "pinned_chrome_labs_migration_complete": true
    }
  }
