---
- name: Perform initial preparation of the system
  hosts: bootstrappers
  roles:
    - { role: partition, tags: partition }
    - { role: bootstrap, tags: bootstrap }
    - { role: switch, tags: switch }

# - name: Perform main provisioning of the system
#   hosts: systems
#   roles:
#     - { role: packaging, tags: packaging }
#     - { role: network, tags: network }
#     - { role: bootloader, tags: bootloader }
#     - { role: user, tags: user }

- name: Perform a cleanup
  hosts: bootstrappers
  roles:
    - { role: unswitch, tags: unswitch }
