---
# TODO: GPG_TTY
# TODO: SSH_AUTH_SOCK
# unset SSH_AGENT_PID
# if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
#   export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
# fi
# - name: Include GPUPG related tasks
#   ansible.builtin.import_tasks:
#     file: gpg.yaml

- name: Include Git related tasks
  ansible.builtin.import_tasks:
    file: git.yaml
#
# TODO: install xdg-user-dirs
# TODO: disable user services with systemctl --user
# TODO: xdg-user-dirs-update --set DOWNLOAD
# XDG_DESKTOP_DIR, XDG_DOCUMENTS_DIR, XDG_DOWNLOAD_DIR, XDG_MUSIC_DIR, XDG_PICTURES_DIR, XDG_PUBLICSHARE_DIR,
# XDG_TEMPLATES_DIR, XDG_VIDEOS_DIR
# TODO: wipe ~/.config/user-dirs.dirs
