---
- name: Include GNUPG related tasks
  ansible.builtin.import_tasks:
    file: gpg.yaml

- name: Include XDG related tasks
  ansible.builtin.import_tasks:
    file: xdg.yaml

- name: Include profile related tasks
  ansible.builtin.import_tasks:
    file: profile.yaml

- name: Include faillock related tasks
  ansible.builtin.import_tasks:
    file: faillock.yaml
