linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gofmt
    - gosec
    - iface
    - inamedparam
    - interfacebloat
    - ireturn
    - maintidx
    - mirror
    - misspell
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - recvcheck
    - revive
    - sloglint
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
  cyclop:
    skip-tests: true
  exhaustive:
    default-signifies-exhaustive: true
  godot:
    scope: all
    capital: true
  iface:
    enable:
      - identical
      - opaque
  misspell:
    locale: US
  prealloc:
    range-loops: true
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  revive:
    rules:
      - name: add-constant
      - name: argument-limit
        arguments: [4]
      - name: atomic
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [10]
      - name: comment-spacings
      - name: comments-density
        exclude: ["**/*_test.go"]
        arguments: [10]
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        arguments: [10]
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
        arguments: [preserveScope, allowJump]
      - name: empty-block
      - name: enforce-repeated-arg-type-style
        arguments: [short]
      - name: error-return
      - name: error-strings
      - name: exported
        arguments: [checkPrivateReceivers, checkPublicInterface]
      - name: filename-format
      - name: flag-parameter
      - name: function-length
        arguments: [40, 60]
      - name: function-result-limit
        arguments: [4]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-alias-naming
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: line-length-limit
        arguments: [80]
      - name: max-control-nesting
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: redefines-builtin-id
      - name: redundant-import-alias
      - name: string-of-int
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value

issues:
  fix: true
  # exclude-rules:
  #   - path: _test\.go
  #     linters:
  #       - gocyclo
  #   - linters:
  #     - staticcheck
  #     text: "SA9003:"
  # exclude-dirs:
  # exclude-files:

run:
  tests: true
  allow-parallel-runners: true

severity:
  default-severity: warning
