---
switch_homectl_cmd: >-
  homectl create
  {{ env_user }}
  --skel=false
  --real-name={{ env_user_name }}
  --email-address={{ env_user_email }}
  --icon-name=face-sad
  --member-of=wheel,video,audio
  --capability-ambient-set=CAP_NET_BIND_SERVICE
  --timezone={{ env_timezone }}
  --language={{ env_locale }}
  --storage=directory
