---
#
# Mapping of global environmental variables. Typically contains
#  XDG quirks or apps behaviour switches suitable for both
#  local and global installations. For example, do not switch
#  DOTNET_ROOT globally as it may interfere with the system
#  package, but do set DOTNET_SYSTEM_NET_DISABLEIPV6.
#
env:
  #
  # Python.
  #
  PYTHONPYCACHEPREFIX: "{{ apps.python.cache }}"
  PYTHON_HISTORY: "{{ apps.python.history }}"

  RUFF_CACHE_DIR: "{{ apps.python.ruff }}"
  IPYTHONDIR: "{{ apps.python.ipython }}"
  UV_TOOL_BIN_DIR: "{{ apps.python.uv_bin }}"
  MYPY_CACHE_DIR: "{{ apps.python.mypy }}"

  #

  #
  # Rust.
  #
  MISE_RUSTUP_HOME: "{{ apps.rust.rustup }}"
  RUSTUP_HOME: "{{ apps.rust.rustup }}"
  MISE_CARGO_HOME: "{{ apps.rust.cargo }}"
  CARGO_HOME: "{{ apps.rust.cargo }}"
  #
  # Go.
  #
  GOPATH: "{{ apps.go.packages }}"
  GOBIN: "{{ apps.go.bin }}"

  #
  # Java.
  #
  GRADLE_USER_HOME: "{{ apps.gradle.home }}"
  MAVEN_OPTS: "-Dmaven.repo.local={{ apps.maven.home }}"
