---
#
# Mapping of global environmental variables. Typically contains
#  XDG quirks or apps behaviour switches suitable for both
#  local and global installations. For example, do not switch
#  DOTNET_ROOT globally as it may interfere with the system
#  package, but do set DOTNET_SYSTEM_NET_DISABLEIPV6.
#
env:
  #
  # Python.
  #
  PYTHONPYCACHEPREFIX: "{{ apps.python.cache }}"
  PYTHON_HISTORY: "{{ apps.python.history }}"

  RUFF_CACHE_DIR: "{{ apps.python.ruff }}"
  IPYTHONDIR: "{{ apps.python.ipython }}"
  UV_TOOL_BIN_DIR: "{{ apps.python.uv_bin }}"
  MYPY_CACHE_DIR: "{{ apps.python.mypy }}"

  #
  # .NET.
  #
  NUGET_HTTP_CACHE_PATH: "{{ apps.dotnet.nuget.http }}"
  NUGET_PACKAGES: "{{ apps.dotnet.nuget.packages }}"
  NUGET_PLUGINS_CACHE_PATH: "{{ apps.dotnet.nuget.plugins }}"

  DOTNET_CLI_HOME: "{{ apps.dotnet.tools }}"
  DOTNET_SYSTEM_NET_DISABLEIPV6: "1"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_GENERATE_ASPNET_CERTIFICATE: "0"
  DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: "0"

  #
  # Rust.
  #
  MISE_RUSTUP_HOME: "{{ apps.rust.rustup }}"
  RUSTUP_HOME: "{{ apps.rust.rustup }}"
  MISE_CARGO_HOME: "{{ apps.rust.cargo }}"
  CARGO_HOME: "{{ apps.rust.cargo }}"

  #
  # JavaScript.
  #
  DENO_DIR: "{{ apps.deno.home }}"
  NODE_REPL_HISTORY: "{{ apps.node.history }}"
  NPM_CONFIG_CACHE: "{{ apps.npm.cache }}"
  PNPM_HOME: "{{ apps.pnpm.home }}"

  #
  # Go.
  #
  GOPATH: "{{ apps.go.packages }}"
  GOBIN: "{{ apps.go.bin }}"

  #
  # Java.
  #
  GRADLE_USER_HOME: "{{ apps.gradle.home }}"
  MAVEN_OPTS: "-Dmaven.repo.local={{ apps.maven.home }}"
