---
#
# Disk identifier as listed in the `/dev/disk/by-id`.
#
bb_disk_id: "{{ undef() }}"

#
# Refer to the files/apart/README.md for more info.
#
bb_schema:
  - name=EFI,type=efi,size=1G
  - name=ROOT,type=root,fs=ext4
