---
#
# Linux kernel package to use. Fallbacks to 'linux' if not defined.
#
# Examples: linux-zen, linux-lts, linux-rt, linux-hardened, and others.
#
dc_kernel: "{{ undef() }}"

#
# CPU microcode package to install.
#
# Typical setups use `intel-ucode` or `amd-ucode`, but generally any package that installs microcode image
#  to `/boot/*-ucode.img` is valid (e.g., intel-real-ucode-git). Resulting image will then be early loaded
#  with the help of bootloader.
#
# This feature is disabled altogether if the value is undefined.
#
dc_microcode: "{{ undef() }}"

#
# List of kernel command-line parameters:
#  - boolean values are treated as flags, i.e. `key: true` results in `key`
#  - list values are merged and rendered with comma separator, i.e. `key: [val, val2]` results in `key=val,val2`
#  - string values are rendered with equals sign, i.e. `key: val` results in `key=val`
#
# Refer to the `foundation.system.kernel` action plugin for more information and implmentation details.
#
dc_cmdline:
  - quiet: true
