---
hb_keyserver: hkps://keys.openpgp.org
hb_digests:
  - SHA512
  - SHA384
  - SHA256
  - SHA224
hb_ciphers:
  - AES
  - AES-192
  - AES-256
  - CAMELLIA128
  - CAMELLIA192
  - CAMELLIA256
  - CAST5
  - IDEA
hb_compressions:
  - Uncompressed
  - ZIP
  - ZLIB

#
# List of keys to generate.
#
# New keys will be generated only if they were not restored from the persist.
#
# Note that in order to integrate existing GnuPG keyring into this role and foundation.user.gpg role, the following
#  persist items must exist:
#  - gpg/keyring: full GnuPG keyring backup with secret keys
#  - gpg/private-keys: archive of private-keys-v1.d/*.key, in order to omit reencryption of keys that occurs after
#    keyring import
#  - gpg/unattended-keys: JSON metadata file of keys from `hb_generate` in the form of array of objects:
#    <master_key_or_subkey>: {"fingerprint": <fpr>, "keygrip": <krp>}
#
hb_generate: "{{ undef() }}"
  # <master-name>:
  #   master:
  #     name: Alice
  #     comment: my key
  #     email: something@.local
  #     expire: 5y
  #     password: qwerty
  #     algo: ecdsa/dsa/rsa
  #     hint: nistp256/2048/4096
  #   subkeys:
  #     <subkey-name>:
  #       type: encr/auth/sigh
  #       #
  #       # SSH key priority for gpg-agent, negative number are highest priority.
  #       #
  #       priority: 100
  #       algo: <>
  #       hint: <>
  #

hb_ssh_agent: true
