---
- name: Include drivers tasks
  ansible.builtin.import_tasks:
    file: drivers.yaml

- name: Include look tasks
  ansible.builtin.import_tasks:
    file: look.yaml

- name: Include x11 related tasks
  ansible.builtin.import_tasks:
    file: x11.yaml

- name: Include wayland related tasks
  ansible.builtin.import_tasks:
    file: wayland.yaml
