---
#
# Headless installation flag.
#
# It is important for tasks that need to know whether machine is actually booted or exist in the transient state
#  (i.e. chroot, container). This flag defines the behavior of the following processes:
#  - service management
#  - temporary files creation
#  - initramrd creation
#  - and others.
#
ba_headless: "{{ undef() }}"

#
# Mount point to do partitioning and bootstrapping.
#
ba_mount_point: "{{ aa_machine_mount }}"

#
# Machine hostname.
#
ba_hostname: "{{ undef() }}"

#
# Number of cores the target machine has.
#
# Used in the various places to specify possible parallelism, but typically is divided by two or four.
#
ba_cores: "{{ undef() }}"

#
# Target machine architecture.
#
# Supported values include: 'x86_64_v3', 'x86_64_v2', and 'aarch64'. This value combines different purposes:
#  - Make use of optimized repositories for newer CPU instruction sets (_v3, _v4)
#  - Prepare for possible ARM transition, at least for non-essential task
#
# The current implementation is far from being ready, as both mentioned reasons above raise a lot of questions about
#  software stack. In either case, here is some further information: https://wiki.cachyos.org/features/optimized_repos/.
#
ba_arch: "x86_64_v2"
