---
#
# Headless installation flag is important for tasks that need to know whether machine is actually booted, i.e. in the
#  consitent and defined state.
#
# This flag is used in:
#  - service management
#  - temporary files creation
#  - initramrd creation
#  - and others.
#
ba_headless: "{{ undef() }}"

#
# Mount point to do partitioning and bootstrapping.
#
ba_mount_point: "{{ aa_machine_mount }}"

#
# Machine hostname.
#
ba_hostname: "{{ undef() }}"

#
# Number of cores the target machine has.
#
# Used in the various places to specify possible parallelism, but typically is divided by two or four.
#
ba_cores: "{{ undef() }}"

#
# Machine arch.
#
ba_arch: "x86_64_v3"
