---
#
# GTK theme name and the corresponding package.
#
gf_gtk: Arc-Dark-solid
gf_gtk_package: arc-solid-gtk-theme

#
# Kvantum (Qt) theme name and the corresponding package.
#
gf_kvantum: KvArcDark
gf_kvantum_package: "{{ undef() }}"
