---
zb_home:
  #
  # Shell (most likely installation script automation).
  #
  - file: ./.bash_profile
  - file: ./.bash_logout
  - file: ./.bash_history
  - file: ./.bashrc
  - file: ./.inputrc

  #
  # History.
  #
  - file: ./.wget-hsts
  - file: ./.lesshst
  - file: ./.sqlite_history
  - file: ./.zcompdump
  - file: ./.ts_node_repl_history
  - file: ./.pdbhistory

  #
  # Xorg.
  #
  - file: ./.xsession-errors
  - file: ./.Xauthority

  #
  # Developer tools.
  #
  - dir: ./.redhat
  - dir: ./.lldb
  - dir: ./.ansible
  - file: ./.yarnrc

  #
  # Apps.
  #
  - dir: ./.java
  - dir: ./.yEd
  - dir: ./.p7zip
  - file: ./.fehbg
  - file: ./.nvidia-settings.rc

zb_gecko:
  #
  # Profile state which stores last used version in order to
  #  maintain proper migration between newer browser versions.
  #
  # - compatibility.ini
  #
  # Profile timestamps.
  #
  # - times.json
  #
  # Firefox Sync.
  #
  - weave
  #
  # Crash reports.
  #
  - Crash Reports
  - crashes
  - minidumps
  #
  # Telemetry and Data Collection.
  #
  - Pending Pings
  - saved-telemetry-pings
  - domain_to_categories.sqlite
  - domain_to_categories.sqlite-journal
  - datareporting
  #
  # HTTP Alternative Service, indicate that another network location
  #  is authoritative for that origin.
  - AlternateServices.bin
  - AlternateServices.txt
  #
  # HTTP Strict Transport Security.
  #
  - SiteSecurityServiceState.bin
  #
  # Bounce Tracking Protection, prevent user tracking via an
  #  intermediary link between the user and the target website.
  #
  - bounce-tracking-protection.sqlite
  #
  # Broadcast Channel API, communication between browsing contexts
  #  (that is, windows, tabs, frames, or iframes) and workers.
  #
  - browser-extension-data
  #
  # PKI Certificate Database and custom trust.
  #
  - cert9.db
  - cert_override.txt
  - pkcs11.txt
  #
  # Intermediate CA Preloading.
  #
  - security_state
  #
  # Favicons.
  #
  - favicons.sqlite
  #
  # Media codecs and DRM (will be downloaded again).
  #
  - gmp-gmpopenh264
  - gmp-widevine
  #
  # Push notifications.
  #
  - notificationstore.json
  #
  # Enhanced Tracking Protection (shield left to the address bar).
  #
  - protections.sqlite
  #
  # Temporary opt in in some test values for the duration of the experiment.
  #
  - shield-preference-experiments.json
  #
  # Service Workers.
  #
  - serviceworker.txt
  #
  # Sites permissions and various settings (zoom, fonts, etc).
  #
  - permissions.sqlite
  - content-prefs.sqlite
  #
  # MIME types associations.
  #
  # - handlers.json
  #
  # Search engines.
  #
  # - search.json.mozlz4
  #
  # LocalStorage, SessionStorage, and other offline data.
  #
  - storage
  - storage.sqlite
  - webappsstore.sqlite
  #
  # Session restoration state.
  #
  # - sessionCheckpoints.json
  # - sessionstore-backups
  #
  # Saved passoword credentials and data.
  #
  # - key4.db
  # - logins.json
  # - logins-backup.json
  #
  # Forms autocomplete history.
  #
  # - formhistory.sqlite
  #
  # Addons (i.e. list of manually installed addons).
  #
  # - addonStartup.json.lz4
  # - addons.json
  #
  # Extensions (i.e. built-in modules + addons).
  #
  #  Downloaded XPI (ZIPs).
  #
  # - extensions
  #
  #  Internal settings, UI pins, permissions.
  #
  - extension-store
  # - extension-store-menus
  # - extension-store-permissions
  #
  #  External settings such as 'Use in private', and others.
  #
  # - extension-preferences.json
  #
  #  Built-in extensions, such as hotfix-intermediate-2018.
  #
  - features
  #
  #  Enumeration of all installed addons
  #   and build-in modules for themes, search engines, autofill, screenshots.
  #
  # - extensions.json
  #
  #  Transactional addons data bucket.
  #
  - storage-sync-v2.sqlite
  #
  # Downloads.
  #
  # - downloads.json
  #
  # Cookies.
  #
  # - cookies.sqlite
  #
  # Firefox Containers.
  #
  # - containers.json
  #
  # Bookmarks, history, and metadata.
  #
  # - places.sqlite
  # - bookmarkbackups
  #
  # Browser settings.
  #
  # - prefs.js
  # - xulstore.json
  # - settings

za_chromium:
  #
  # Generic cache.
  #
  - Cache
  - CachedData
  #
  # JS/Wasm cache.
  #
  - Code Cache
  #
  # GPU Cache.
  #
  - GPUCache
  - DawnWebGPUCache
  - DawnGraphiteCache
  - GrShaderCache
  - SharedCache
  - VideoDecodeStats
  #
  # Version-based compression dictionaries.
  #
  - Shared Dictionary
  #
  # Crash Reports.
  #
  - Crashpad
  - Crash Reports
  #
  # Binary files.
  #
  - blob_storage
  - File System
  #
  # Various site data.
  #
  - IndexedDB
  - WebStorage
  - Local Storage
  - Session Storage
  - Service Worker
  - SharedStorage
  #
  # Electron logs.
  #
  - chrome_debug.log
  - logs
  #
  # Cross-sites relations (CORS, permissions, data sharing).
  #
  - FirstPartySetsPreloaded
  - first_party_sets.db
  - first_party_sets.db-journal
  #
  # "intelligence and machine learning" for user experience,
  #  whatever that means.
  #
  - segmentation_platform
  - Segmentation Platform
  #
  # Google Cloud Messaging.
  #
  - GCM Store
  #
  # Experimental APIs enabled by the site.
  #
  - OriginTrials
  - PersistentOriginTrials
  #
  # API that allows a provider to store some signed data in browser,
  #  which can be then verified by another party.
  #
  - TrustTokenKeyCommitments
  - Trust Tokens
  - Trust Tokens-journal
  #
  # Hints and machine learning models received from the remote
  #  Chrome Optimization Guide Service.
  #
  - OptimizationHints
  - optimization_guide_hint_cache_store
  #
  # Commerce and shopping related projects.
  #
  - BudgetDatabase
  - parcel_tracking_db
  - discounts_db
  - heavy_ad_intervention_opt_out.db
  - heavy_ad_intervention_opt_out.db-journal
  #
  # Background site tracking, i.e. favicon or page title change.
  #
  - Site Characteristics Database
  #
  # Sync.
  #
  - trusted_vault.pb
  - Sync Data
  #
  # Topics API, instead of tracking user with third-party cookies,
  #  let the browser provide information about about user topics.
  #
  - BrowsingTopicsSiteData
  - BrowsingTopicsSiteData-journal
  - BrowsingTopicsState
  - InterestGroups
  #
  # DIPS, a part of BTM(Bounce Tracking Mitigation). Its goal is to
  #  prevent user tracking via an intermediary link between the user and
  #  the target website.
  #
  - DIPS
  - DIPS-journal
  #
  # Media Device Salt, allows media devices (i.e., microphones and cameras)
  #  IDs to be unique per origin (so there is no cross-origin tracking),
  #  yet be mappable back to the real device IDs.
  #
  - MediaDeviceSalts
  - MediaDeviceSalts-journal
  #
  # App Service abstraction that connects:
  #  1) app consumers: permissions or settings pages, handlers for URLs,
  #     MIME types or intents, etc.
  #  2) app publishers: built-in apps, extension-backed apps, PWAs.
  #
  - PreferredApps
  #
  # HTTP/2 and SPDY state.
  #
  - Network Persistent State File
  #
  # Preload statistics of misses and hits.
  #
  - Network Action Predictor
  - Network Action Predictor-journal
  #
  # Favicons.
  #
  - Favicons
  - Favicons-journal
  #
  # In-Product Help, i.e. various UI popups such as 'Make Chromium faster'.
  #
  - Feature Engagement Tracker
  #
  # Safe Browsing, showing warning messages for unsafe sites.
  #
  - Safe Browsing
  - Crowd Deny
  - Safe Browsing Cookies
  - Safe Browsing Cookies-journal
  #
  # Client-side anti-spoof heuristics, warning for lookalikes based on
  #  edit distance and skeleton similarity.
  #
  - SafetyTips
  #
  # SSL ecosystem components, e.g. Certificate Transparency (CT).
  #
  - SSLErrorAssistant
  - PKIMetadata
  - SCT Auditing Pending Reports
  - CertificateRevocation
  #
  # NEL/Reporting V0/Reporting V1, response header is used to configure
  #  network request logging.
  #
  - Reporting and NEL
  - Reporting and NEL-journal
  #
  # New Tab Page.
  #
  - Top Sites
  - Top Sites-journal
  #
  # HTTP Strict Transport Security.
  #
  - TransportSecurity
  #
  # Generic downloads service.
  #
  - Download Service
  - shared_proto_db
  #
  # Links of origin-specific data across multiple origins, for example,
  #  passwords that should be shared between a website and
  #  the native application.
  #
  - Affiliation Database
  - Affiliation Database-journal
  #
  # Third-Party Cookie Deprecation compat.
  #
  - TpcdMetadata
  #
  # Privacy Sandbox.
  #
  - PrivacySandboxAttestationsPreloaded
  #
  # Filtering subsystem, used by internal ad filter and safe browsing.
  #
  - Subresource Filter
  #
  # Autofill.
  #
  - AutofillStates
  - AutofillStrikeDatabase
  #
  # File types database, used in 'This file can harm'.
  #
  - FileTypePolicies
  #
  # Hyphenation dictionaries.
  #
  - hyphen-data
  #
  # Media Engagement database, list of whitelisted autoplay sites.
  #
  - MEIPreload
  #
  # Unsecure passwords database.
  #
  # - ZxcvbnData
  #
  # Omnibox autocompletion.
  #
  - OnDeviceHeadSuggestModel
  #
  # Cookies.
  #
  # - Cookies
  #
  # History.
  #
  # - History
  # - History-journal
  #
  # Preferences.
  #
  # - Preferences
  #
  # Extensions.
  #
  # - Extensions
  - Extension Rules
  - Extension Scripts
  - Extension State
  - component_crx_cache
