update_check = false
auto_sync = false

history_filter = [
    "^exit",
    "^clear",
    "^reset",
    "^nu",
    "^fish",
    "^bash",
    "^sh"
]

keymap_mode = "vim-insert"
scroll_exits = false
style = "compact"
