---
#
# Refer to the `./roles/ba-prelude/ba-shared/defaults/main.yml`.
#
ba_headless: true
ba_mount_point: /mnt
ba_hostname: example
ba_cores: 8
ba_arch: x86_64_v2
ba_locale: en_US.UTF-8

#
# Refer to the `./roles/ba-prelude/bb-partition/defaults/main.yml`.
#
bb_disk_id: ata-SSD
bb_schema:
  - name: EX-EFI
    table:
      type: efi
      size: 1G
    fs:
      type: vfat
    mount:
      path: /efi

  - name: EX-ROOT
    table:
      type: root
      size: 85%
    fs:
      type: ext4
    mount:
      path: /

  - name: EX-VOLT
    table:
      type: linux
      size: auto
    fs:
      type: ext4

#
# Refer to the `./roles/ba-prelude/bc-bootstrap/defaults/main.yml`.
#
bc_root_password: example
bc_keymap: us
bc_timezone: Europe/Berlin
