---
ba_headless:  true
ba_mount_point: /mnt
ba_hostname: example
ba_cores: 8
ba_arch: x86_64_v2
ba_locale: en_US.UTF-8

bb_disk_id: ata-SSD
bb_schema:
  - name=EX-EFI,type=efi,size=1G
  - name=EX-ROOT,type=root,fs=xfs,size=85%
  - name=EX-SWAP,type=swap,size=8G
  - name=EX-VOLT,type=linux,fs=ext4

bc_root_password: example
bc_mountopts_root: async,noatime,auto,dev,exec,noiversion,suid,rw,nouser,dax=always,nodiscard,noquota
bc_mountopts_efi: "sync,noatime,auto,dev,exec,noiversion,suid,rw,nouser,fmask=0023,dmask=0022,check=s,discard,\
  errors=remount-ro,iocharset=utf8,tz=UTC,flush,utf8"
bc_keymap: us
bc_timezone: Europe/Berlin
