---
#
# Refer to the `./roles/ca-catalyst/ca-shared/defaults/main.yml`.
#
ca_name: user
ca_password: qwerty
ca_info_short: User
ca_info_full: Example User
ca_info_alt: Exemple d'Utilisateur
ca_info_mail: example@.local
