---
#
# Refer to the `./roles/ea-apex-user/fa-shared/defaults/main.yml`.
#
fa_layout: dot

fa_dir_home: "/home/{{ ca_name }}"
fa_dir_config: "{{ fa_dir_home }}/.config"
fa_dir_cache: "{{ fa_dir_home }}/.cache"
fa_dir_share: "{{ fa_dir_home }}/.local/share"
fa_dir_state: "{{ fa_dir_home }}/.local/state"
fa_dir_bin: "{{ fa_dir_home }}/.local/bin"

fa_dir_subs:
  XDG_CONFIG_HOME: "{{ fa_dir_config }}"
  XDG_CACHE_HOME: "{{ fa_dir_cache }}"
  XDG_DATA_HOME: "{{ fa_dir_share }}"
  XDG_STATE_HOME: "{{ fa_dir_state }}"

fa_dir_xdg:
  download: "{{ fa_dir_home }}/dls"
  documents: "{{ fa_dir_home }}/env"
  hub: "{{ fa_dir_home }}/hub"

  pictures: "{{ fa_dir_home }}/media/pics"
  videos: "{{ fa_dir_home }}/media/vids"
  music: "{{ fa_dir_home }}/media/music"

  templates: "{{ fa_dir_home }}/misc/templates"
  publicshare: "{{ fa_dir_home }}/misc/public"
  desktop: "{{ fa_dir_home }}/misc/desktop"
