---
#
# Refer to the `./roles/ga-apex-desktop/ga-shared/defaults/main.yml`.
#
ga_stack:
  - type: nvidia
    drivers:
      - nvidia

#
# Refer to the `./roles/ga-apex-desktop/ga-shared/defaults/main.yml`.
#
ga_monitors:
  primary:
    workspaces: 8
    width: 1920
    height: 1080
    refresh: 60
    x11: DFP-1
    wayland: HDMI-A-1

    notifications: true
    scratch: Scratch

#
# Refer to the `./roles/ga-apex-desktop/gd-media/defaults/main.yml`.
#
gd_cards:
  main:
    exclusive: true
    frequency: 48000
    format: S24
    channels: [FL, FR]

    selectors:
      device:
        device.form-factor: internal
      input:
        api.alsa.card.name: HD-Audio Generic
        api.alsa.pcm.stream: capture
      output:
        api.alsa.card.name: HD-Audio Generic
        api.alsa.pcm.stream: playback

    inputs:
      jacks:
        Front Mic:
        Line:
        Rear Mic:
      enumerations:
        Input Source,0:
        Input Source,1:
        Loopback Mixing:
      elements:
        Front Mic:
          type: [switch, volume]
          direction: capture
        Front Mic Boost:
          type: [volume]
          direction: capture
        Line:
          type: [switch, volume]
          direction: playback
        Line Boost:
          type: [volume]
          direction: playback
        Capture,0:
          type: [switch, volume]
        Capture,1:
          type: [switch, volume]
        Digital:
          type: [volume]
        Rear Mic:
          type: [switch, volume]
          direction: playback
        Rear Mic Boost:
          type: [volume]

    outputs:
      jacks:
        Front Headphone:
        Line Out CLFE:
        Line Out Front:
        Line Out Surround:
        SPDIF Phantom:
      enumerations:
        Auto-Mute Mode:
      elements:
        Master:
          type: [switch, volume]
        Headphone:
          type: [switch, volume]
        PCM:
          type: [volume]
        Front:
          type: [switch, volume]
        Surround:
          type: [switch, volume]
        Center:
          type: [switch, volume]
        LFE:
          type: [switch, volume]
        Side:
          type: [switch, volume]
        IEC958:
          type: [switch]
        IEC958 Default PCM:
          type: [switch]
    acp:
      output:analog-stereo-headset+input:analog-stereo-headset:
        type: profile
        inputs:
          - analog-stereo-headset
        outputs:
          - analog-stereo-headset
      analog-stereo-headset:
        type: mapping
        label: analog-stereo-headset
        device: front:%f
        priority: 10
        inputs:
          - analog-input-microphone-headset
        outputs:
          - analog-output-headphones
      analog-input-microphone-headset:
        type: input-path
        label: analog-input-microphone-headset
        priority: 10
        jacks:
          Rear Mic:
        elements:
          Digital:
          Capture,0:
          Rear Mic Boost:
        enumerations:
          Input Source,0:
            option: Rear Mic
            description: input-microphone
          Input Source,1:
            option: Rear Mic
            description: input-microphone
          Loopback Mixing:
            option: Disabled
            description: input
      analog-output-headphones:
        type: output-path
        label: analog-output-headphones
        priority: 10
        jacks:
          Line Out Front:
        elements:
          Front:
          PCM:
          Master:
        enumerations:
          Auto-Mute Mode:
            option: Disabled
            description: output-headphones
