---
#
# `aa-global` defines global variables for the entire playbook.
#
#  Consider the following recommendations:
#   1) `aa` should define the most basic variables
#   2) `[a-z]a` should define shared variables that are used:
#       by other subroles (for `ba`, it is `bb`, `bc`, ...)
#       by other roles (for `ba`, it is `db`, `cf`, ...)
#   3) `[a-z][b-z]` should define local variables (for `bc`, only `bc` uses it)
#

#
# A path to the persistance directory on the control node that is used to pull and push data using the
#  `foundation.persist.*` actions.
#
# It follows the simple `key/value` pattern, which physically represented as directory and file on the filesystem level,
#  respectively. Files may be either raw shell outputs, or tar archives. Its content is not encrypted.
#
# This directory must exist. Its ownership is transferred to its elements, even when running as another user (i.e. even
#  when systemd-nspawn is running as root, persist items will have the same permissions as directory).
#
aa_persist: "{{ undef() }}"

#
# BE VERY CAUTIOUS WHEN RUNNING THIS FLAG ON EXISTING SYSTEMS!
# An unsafe flag that will forcefully clean installation targets state.
#
# This means that for the most of targets, it would ENTIRELY clean their configuration, cache and state directories.
#
# Must be either `always` or `never`.
#
aa_wipe: "{{ undef() }}"
