[settings]
experimental = true
legacy_version_file = true

log_level = "warn"

env_file = ".env"
plugin_autoupdate_last_check_duration = "0"

python_precompiled_os = "unknown-linux-gnu"
python_precompiled_arch = "x86_64_v2"


[settings.status]
show_tools = true
show_env = true
