---
#
# Whenever enable save feature for volumes and fallback source and sink.
#
gd_save: false

#
# Video capture support.
#
gd_video_v4l2: false
gd_video_libcamera: false

#
# Midi support.
#
gd_midi: false

#
# Jack support.
#
gd_jack: false

#
# Bluez5 support.
#
gd_bluetooth: false

#
# Noise suppression, and its VAD Threshold.
#
gd_rnnoise: true
gd_rnnoise_threshold: 50.0

#
# Loopback device that basically acts as a virtual output that may be useful to omit some of the applications from
#  recordings.
#
gd_loopback: true

#
# Percentage of computation complexity to quality.
#
gd_resampling: 0.6

#
# Application quantum (buffer size) for audio processing.
#
gd_quantum_min: 256
gd_quantum_default: 1024
gd_quantum_max: 4096

#
# Realtime priority.
#
gd_realtime_nice: -10
gd_realtime_priority: 80

#
# If hard limit is required instead, there is `volume-limit` in the acp.
#
# Can be measured using `wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.5`.
#
gd_volume_output: 1.0
gd_volume_input: 1.0

#
# List of apps that have full access to the mixers. Extremely useful in case of WebRTC automatic gain control.
#
gd_whitelist:
  - pavucontrol
  - helvum
  - waybar
  - wpctl

#
# Alsa card profile configuration allows to set up the way PulseAudio/PipeWire talks to the alsa.
#
# The algorithm for ACP is common for both PulseAudio and PipeWire as they share the same codebase, though PipeWire
#  includes a handly `spa-acp-tool` utility which makes debugging easier.
#
# For more information about syntax and entities, refer to the:
#  https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/mixer/profile-sets/default.conf
#  https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/mixer/paths/analog-output.conf.common
#
# Having a custom profile set is beneficial in the number of ways:
#  - blacklist ports that have never been used in the usual headphones setup, but still visible in the settings
#  - blacklist the whole screen of different 7.1, 5.1, ... profiles that have no use
#  - solve various compatibility issues such as crackling sound when plugging headphones because of the line boost
#  - correct profile and device naming instead of generic Analog Stereo
#  - complete control over all alsa mixers, including boosts, loopback, and auto-mute
#  - gain a 0.000001s sound server startup boost! :)
#
# The are also the well-known keys for most of the units:
#  Profiles: https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/alsa-mixer.c#n4735
#  Mappings: https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/alsa-mixer.c#n4566
#  Options: https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/alsa-mixer.c#n2706
#  Paths: https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/modules/alsa/alsa-mixer.c#n2794
#
gd_cards: "{{ undef() }}"
  # <name>:
  #   #
  #   # Create a rule that would disable any other devices other than this.
  #   #
  #   exclusive: <bool>
  #   #
  #   # Sample rate.
  #   #
  #   # Can be examined with `grep rates /proc/asound/card0/codec\#0`.
  #   #
  #   frequency: <int>
  #   #
  #   # Sample format (https://docs.pipewire.org/page_pulse_modules.html).
  #   #
  #   # Can be examined with `grep bits /proc/asound/card0/codec\#0`. Examples:
  #   #  - S32LE
  #   #  - S16BE
  #   #  - U8
  #   #
  #   format: <depth>
  #   #
  #   # Channel positions.
  #   # Examples:
  #   #  FL: Front Left
  #   #  FR: Front Right
  #   #  RL: Rear Left
  #   #  RR: Rear Right
  #   #  FC: Front Center
  #   #  LFE: Low Frequency Effects (subwoofer)
  #   #
  #   channels: [<one>, <two>, ...]
  #   #
  #   # Selectors specific to this card.
  #   #
  #   # Can be examined with 'pw-cli info all'.
  #   #
  #   selectors:
  #     #
  #     # Dictionary of card selectors.
  #     #
  #     device:
  #     #
  #     # Dictionary of input selectors.
  #     #
  #     input:
  #     #
  #     # Dictionary of output selectors.
  #     #
  #     output:
  #   #
  #   # ALSA mappings.
  #   #
  #   # Can be examined with:
  #   #  'amixer -c0 scontents'
  #   #  'alsactl dump-state' (type BOOLEAN, INTEGER, ENUMERATED)
  #   #  'alsa-info.sh --with-alsactl --no-upload'
  #   #  'alsa-info.sh --with-amixer --no-upload'
  #   #
  #   inputs:
  #     #
  #     # Dictionary of jacks.
  #     #
  #     # Can be examined via `amixer -c0 contents | grep Jack`.
  #     #
  #     jacks:
  #     #
  #     # Dictionary of enumerations.
  #     #
  #     # Can be examined via `amixer -c0 scontents | grep enum -B1 -A1`.
  #     #
  #     enumerations:
  #     #
  #     # Dictionary of elements.
  #     #
  #     # Can be examined with `amixer -c0 scontents | grep -P 'switch|volume' -B1 -A2`
  #     #
  #     elements:
  #       <element>:
  #         #
  #         # Type of elements. Usually, boost have only volume, while microphones and speakers have both switch and
  #         #  volume. (listed in the `Capabilities:` section of the `amixer` output).
  #         #
  #         type: [<switch|volume>, ...]
  #         #
  #         # Element direction (selector, not purpose). Optional, should only be used for those element that are bugged.
  #         # (listed in the `Playback channels:` and `Capture channels:` sections of the `amixer` output).
  #         #
  #         direction: <playback|capture>
  #   outputs:
  #     jacks:
  #     enumerations:
  #     elements:
  #   #
  #   # Card Profile definition.
  #   #
  #   acp:
  #     <profile-name>:
  #       type: profile
  #       inputs: []
  #       outputs: []
  #     <mapping-name>:
  #       type: mapping
  #       #
  #       # Supports well-known keys.
  #       #
  #       label: <label>
  #       device: <selector>
  #       priority: <int>
  #       inputs: []
  #       outputs: []
  #     <path-name>:
  #       type: <input|output>-path
  #       #
  #       # Supports well-known keys.
  #       #
  #       label: <label>
  #       priority: <int>
  #       jacks: {}
  #       elements: {}
  #       enumerations:
  #         <enum>:
  #           #
  #           # The value of the enumeration, i.e. `Disabled` or `Rear`/`Front`.
  #           #
  #           option: <option>
  #           #
  #           # Supports well-known keys.
  #           #
  #           description: <description>
  #
