---
ia_spotify_launcher_user_layout:
  default: "{{ fa_dir_share }}/spotify-launcher"
  dot:
    link: "{{ fa_dir_home }}/.spotify-launcher"

ia_vscode_user_layout:
  default: "{{ fa_dir_config }}/Code"
  dot: "{{ fa_dir_home }}/.vscode/data"
  xdg: "{{ fa_dir_state }}/vscode"

ia_browsers:
  - type: gecko
    package: firefox
    home:
      default: "{{ fa_dir_home }}/.mozilla/firefox"
      xdg:
        link: "{{ fa_dir_state }}/firefox"
    cache:
      default: "{{ fa_dir_cache }}/mozilla/firefox"

  - type: chromium
    package: chromium
    flags: "{{ fa_dir_config }}/chromium-flags.conf"
    home:
      default: "{{ fa_dir_config }}/chromium"
      dot: "{{ fa_dir_home }}/.chromium"
      xdg: "{{ fa_dir_state }}/chromium"
    cache:
      default: "{{ fa_dir_cache }}/chromium"

  - type: chromium
    package: vivaldi
    flags: "{{ fa_dir_config }}/vivaldi-stable.conf"
    home:
      default: "{{ fa_dir_config }}/vivaldi"
      dot: "{{ fa_dir_home }}/.vivaldi"
      xdg: "{{ fa_dir_state }}/vivaldi"
    cache:
      default: "{{ fa_dir_cache }}/vivaldi"
